Data:
  train_data_root: "/data/lyh/Affwild2_examples/VA_splits_w300_s200/Train_Set"
  val_data_root: "/data/lyh/Affwild2/cropped_aligned/val/video6"
  loader:
    batch_size: 32
    num_workers: 4
    pin_memory: True
    test_batch_size: 32

Model:
  model_name: Model
  bin_num: 1
  num_layer: 4
  kernel_size: 15
  out_dim: 256
  d_state: 8
  d_conv: 4 
  expand: 1
  pretrained_path: /data/lyh/8th_result/logs/log/mae_1024_mamba_fold0/ckpt_epoch_22_iter_78.pt



Log:
  log_file_path: "/data/lyh/8th_result/logs/log/"
  log_file_name: "test.log"

HP:
  loss: ccc
  epoch: 40
  warmup: 2
  lr: 0.0003
  weight_decay: 0.001
  optimizer: AdamW
  dropout: 0.3
